apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    metadata:
      labels:
        nodegroup-type: compute
        nodegroup-role: worker
        environment: dev
        nodepool: karpenter
        kubernetes.io/os: linux
        node-lifecycle: on-demand

    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default

      requirements:
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["t", "m", "r"]

        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["t3", "m3", "r3"]

        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]

        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]

        - key: kubernetes.io/os
          operator: In
          values: ["linux"]

        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]

      expireAfter: 720h
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
