apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  instanceProfile: "${instance_profile}"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${cluster_name}"
  securityGroupSelectorTerms:
    - tags:
        kubernetes.io/cluster/${cluster_name}: "owned"
  amiSelectorTerms:
    - name: "amazon-eks-node-${kubernetes_version}-v*"
      architecture: "x86_64"