apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crd2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Kristof-oe/argocd_szakd.git
    targetRevision: HEAD
    path: karpenter/monitor
  destination:
    namespace: monitor
    server: https://kubernetes.default.svc

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true



  


