apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  dependsOn:
    - crd
  project: default
  source:
    chart: karpenter
    namespace: karpenter
    repoURL: oci://public.ecr.aws/karpenter/karpenter
    targetRevision: 1.3.3
    helm:
      values: |
        settings:
          clusterName: dev-szakd-eks
          interruptionQueue: karpenter-interruption
          resource:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
        controller:
          serviceAccount:
            create: true
            name: karpenter
            annotations:
              "eks\\.amazonaws\\.com/role-arn": arn:aws:iam::650251684473:role/karpenter-controller

destination:
  server: https://kubernetes.default.svc
  namespace: karpenter
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true

