
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: back-monitor
  namespace: monitoring
  labels:
    app: django
    release: kube-prometheus-stack
spec:
  podMetricsEndpoints:
  - interval: 10s
    portNumber: 8000
    path: /metrics
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      operated-prometheus: "true"
      