apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  dependsOn:
    - crd
  project: default
  source:
    chart: ${chart}
    namespace: ${namespace}
    repoURL: oci://public.ecr.aws/karpenter/karpenter
    targetRevision: ${version}
    helm:
      values: |
        settings:
          clusterName: ${cluster_name}
          interruptionQueue: ${interruptionQueue}
          resource:
            requests:
              cpu: ${reqcpu}
              memory: ${reqmemory}
            limits:
              cpu: ${limitcpu}
              memory: ${limitmemory}
        controller:
          serviceAccount:
            create: true
            name: ${serviceAccountname}
            annotations:
              "eks\\.amazonaws\\.com/role-arn": ${serviceAccountarn}

destination:
  server: https://kubernetes.default.svc
  namespace: ${namespace}
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true

