apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitor
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    namespace: monitoring
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: latest
    helm: 
      values: |
      prometheus:
        prometheusSpec:
          serviceMonitorSelectorNilUsesHelmValues: false
          externalLabels:
            environment: "${environment}"

  destination:
    server: https://kubernetes.default.svc
    namespace: monitor
syncPolicy:
  automated:
    selfHeal: true
    prune: true
  syncOptions:
    - CreateNamespace=true

 



  


